version: '3.8'

services:
  worklenz-static-site:
    image: kithceydigital/worklenz-astro:latest
    container_name: worklenz-nginx
    restart: unless-stopped
    ports:
      - "80:80"

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
