name: Docker Deploy to Docker Hub

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: kithceydigital/worklenz-astro
  IMAGE_TAG: latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js and Install Deps
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: |
          corepack enable
          pnpm install
          pnpm run build

      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG .

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker Image
        run: docker push $IMAGE_NAME:$IMAGE_TAG
