name: Deploy to Server
# Trigger the workflow on push events to the main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH and Deploy
        env:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            SSH_HOST: ${{ secrets.SSH_HOST }}
            SSH_USER: ${{ secrets.SSH_USER }}
            PROJECT_DIR: ${{ secrets.PROJECT_DIR }}
        run: |
          # Setup SSH connection
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh-keyscan -H "$SSH_HOST" >> ~/.ssh/known_hosts

          # Define the deployment script
          DEPLOY_SCRIPT="
          set -e
          echo "--- Starting deployment on server ---"
          cd $PROJECT_DIR
          echo "--- Pulling latest code from main branch ---"
          git pull origin main
          echo "--- Installing dependencies with pnpm ---"
          # Ensure pnpm is available, you might need to install it globally on your server first
          # Example: npm install -g pnpm
          pnpm install --frozen-lockfile
          echo "--- Building static files ---"
          pnpm run build
          echo "--- Deployment finished successfully ---"
          "

          # Execute the script on the remote server
          ssh -i private_key ${SSH_USER}@${SSH_HOST} "${DEPLOY_SCRIPT}"
